# <<: (merge) NOT supported in GitHub workflows
# Possible use cases
#  - specify "path" once and reuse it
#  - specify "env" once and reuse it
name: Anchors and Aliases Workflow
on: [workflow_dispatch]

jobs:
  job1: &anchor
    runs-on: ubuntu-22.04
    steps:
      - name: Command Execution
        run: echo "Execute command..."
  job2:
    *anchor
