name: Invoke scripts workflow

on: [workflow_dispatch]              # Allows triggering the workflow manually

jobs:
  invoke-script-job:
    runs-on: ubuntu-24.04
    defaults:                        # Defines defaults for the current job
      run:
        working-directory: ./scripts/workflow_invoked # Sets working directory for all "run" in the current job; needed to tell the workflow where to look for the scripts
    steps:
      # Ref: https://stackoverflow.com/questions/64405836/no-such-file-or-directory-on-any-run-step#:~:text=If%20you%20are%20accessing%20files%20from%20the%20repo%2C%20you%20need%20to%20perform%20a%20checkout%20first%3A
      # To be able to access the project folders, you first have to checkout.
      # A list of GitHub actions can be found at https://github.com/actions/<action-name> (for instance, https://github.com/actions/checkout). Alternatively, you can inspect the Marketplace.
      - name: Checkout
        uses: actions/checkout@v6                  # "uses" invokes an action (usage at https://github.com/actions/checkout/README.md)
                                                   #   with --> map of input parameters for the actions (key-value pairs)
        
      - name: Run a script (specify interpreter)
        run: bash script1.sh                       # "run" executes commands

      - name: Run multiple commands
        run:  |        # Required to execute multiple commands in the same shell
          bash script1.sh
          bash script2.sh
